name: Testing - Reusable Workflow
on: 
  workflow_call:
    inputs:
      ingress-rul:
        description: Provide the Ingress URL
        required: true
        type: string


jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - env:
          URL: '${{ inputs.ingress-rul }}'
        run: |
          curl https://$URL/live -s -k | jq -r .status | grep -i live